"""Added about_me and last_seen in User model

Revision ID: 510efefe4b14
Revises: cf8ac8d31e6c
Create Date: 2019-10-22 15:17:45.674641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510efefe4b14'
down_revision = 'cf8ac8d31e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
